### ISSUE TITLE
alexa_google bind issue

### ISSUE THREAD

**Issue by alam121** [tuya/tuya-ui-bizbundle-android-demo#25]
In alexa_google bind, google assistant activity is not working:

Results in the following prompt:

com.testbizbundle.demo E/service not implement: com.tuya.smart.api.service.FlutterSchemeService

Any idea on what should I look at?

**Comment by Innocencellh** [comment]
thank you for your feedback . The above log was provided by our internal developer , which will be helpful for debugging . You could ignore it as the issue is not caused by the dependency . In your case , you would better confirm if you had configured the `app_scheme`  currently . For more details you could see : 
https://developer.tuya.com/en/docs/app-development/Voice_skill_binding?id=Kamzstrvmvf2t
