### ISSUE TITLE
Energy saving mini app 

### ISSUE THREAD

**Issue by gokselsina** [tuya/tuya-ui-bizbundle-android-demo#53]
When we go to the energy saving mini app and click buy, we get a warning. What is the reason for this? Is the energy-saving miniapp Tuya's own application? Can we use this miniapp for iOS as well?![Screenshot_2023-11-27-14-58-10-901_com.enginare.smart.jpg](https://github.com/tuya/tuya-ui-bizbundle-android-demo/assets/115628199/16a2ae5a-f408-4ddf-a1da-050b29d91191)

**Comment by zjutwhw** [comment]
Hello, the energy saving mini app can not only be used in the tuya's own application but can also be integrated into other apps through the AppSDK method. If you want to integrate the energy saving mini app into your product, you need to complete the relevant product information configuration; otherwise, it may result in an error. If you would like to learn more about the integration process, please contact our dedicated personnel（email：zhanghan.zheng@tuya.com）.

**Comment by gokselsina** [comment]
Thx 🙏🏻
